spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?useSSL=false
    username: USER_NAME
    password: USER_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Minsk

weatherapi:
  url: https://rapidapi.com/weatherapi/api/weatherapi-com
  api-key: USER_KEY
  city: USER_CITY
